# Generated by Django 3.1.3 on 2020-12-21 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstabelecimentoSaude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cnes', models.CharField(max_length=8, unique=True, verbose_name='CNES')),
                ('nome_fantasia', models.CharField(max_length=300)),
                ('razao_social', models.CharField(blank=True, max_length=300, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=300, null=True)),
                ('endereco', models.CharField(blank=True, max_length=300, null=True)),
                ('complemento', models.CharField(blank=True, max_length=300, null=True)),
                ('bairro', models.CharField(blank=True, max_length=300, null=True)),
                ('cep', models.CharField(blank=True, max_length=300, null=True)),
                ('telefone', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeFederativa',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('sigla', models.CharField(max_length=2, unique=True)),
                ('nome', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('data_nascimento', models.DateField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfissionalVinculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='administracao.estabelecimentosaude')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='administracao.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True)),
                ('nome', models.CharField(max_length=60)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='administracao.unidadefederativa')),
            ],
        ),
        migrations.CreateModel(
            name='EstoqueVacina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.PositiveIntegerField(default=0)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to='administracao.estabelecimentosaude')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estabelecimentos', to='administracao.vacina')),
            ],
        ),
        migrations.AddField(
            model_name='estabelecimentosaude',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='administracao.municipio'),
        ),
    ]
