# Generated by Django 3.1.3 on 2020-12-21 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoVacina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cartao', to='administracao.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='VacinaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartao_vacina.cartaovacina')),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacinas_aplicadas', to='administracao.estabelecimentosaude')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas_aplicadas', to='administracao.usuario')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracao.vacina')),
            ],
        ),
        migrations.AddField(
            model_name='cartaovacina',
            name='vacinas',
            field=models.ManyToManyField(through='cartao_vacina.VacinaUsuario', to='administracao.Vacina'),
        ),
    ]
